export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { imageData, mimeType } = req.body;
    if (!imageData || !mimeType) return res.status(400).json({ error: 'Missing imageData or mimeType' });

    // Convert base64 to binary and send as multipart form
    const buffer = Buffer.from(imageData, 'base64');
    const ext = mimeType.split('/')[1] || 'jpg';
    const filename = 'image.' + ext;

    const formData = new FormData();
    const blob = new Blob([buffer], { type: mimeType });
    formData.append('media', blob, filename);

    const aiornot = await fetch('https://api.aiornot.com/v1/reports/image', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + process.env.AIORNOT_API_KEY,
      },
      body: formData
    });

    const data = await aiornot.json();
    if (data.error || data.detail) return res.status(500).json({ error: data.error || data.detail });

    // Map aiornot response to our format
    const isAI = data.report?.verdict === 'ai';
    const aiScore = Math.round((data.report?.ai?.confidence || 0) * 100);
    const realScore = Math.round((data.report?.human?.confidence || 0) * 100);

    const verdict = aiScore >= 60 ? 'AI_GENERATED' : aiScore <= 40 ? 'AUTHENTIC' : 'UNCERTAIN';

    const result = {
      verdict,
      confidence: Math.max(aiScore, realScore),
      ai_probability: aiScore,
      authentic_probability: realScore,
      indicators: [
        { type: isAI ? 'ai' : 'real', text: isAI ? 'Image flagged as AI generated by detection model' : 'Image classified as human/real by detection model' },
        { type: 'neutral', text: 'AI confidence score: ' + aiScore + '%' },
        { type: 'neutral', text: 'Authentic confidence score: ' + realScore + '%' },
      ],
      summary: isAI
        ? 'This image was likely generated by an AI model with ' + aiScore + '% confidence.'
        : 'This image appears to be authentic with ' + realScore + '% confidence.'
    };

    return res.status(200).json(result);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
