export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { imageData, mimeType } = req.body;
    if (!imageData || !mimeType) return res.status(400).json({ error: 'Missing imageData or mimeType' });

    const buffer = Buffer.from(imageData, 'base64');
    const ext = mimeType.split('/')[1] || 'jpg';

    // --- 1. AI or Not for accurate verdict ---
    const formData = new FormData();
    formData.append('image', new Blob([buffer], { type: mimeType }), 'image.' + ext);

    const aiornotRes = await fetch('https://api.aiornot.com/v2/image/sync?only[]=ai_generated', {
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + process.env.AIORNOT_API_KEY },
      body: formData
    });
    const aiornotData = await aiornotRes.json();
    if (aiornotData.detail) return res.status(500).json({ error: JSON.stringify(aiornotData.detail) });

    const ag = aiornotData.report?.ai_generated;
    if (!ag) return res.status(500).json({ error: 'No ai_generated data', debug: JSON.stringify(aiornotData).slice(0, 300) });

    const rawAI = (ag.ai?.confidence || 0) * 100;
    const isAI = ag.verdict === 'ai';
    const aiScore = isAI ? Math.min(95, Math.max(55, Math.round(rawAI))) : Math.min(45, Math.max(5, Math.round(rawAI)));
    const realScore = 100 - aiScore;
    const verdict = aiScore >= 60 ? 'AI_GENERATED' : aiScore <= 40 ? 'AUTHENTIC' : 'UNCERTAIN';

    const generators = ag.generator || {};
    const topGenerators = Object.entries(generators)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 2)
      .filter(([, score]) => score > 0.3)
      .map(([name, score]) => ({ type: 'ai', text: name.replace(/_/g, ' ') + ' generator: ' + Math.round(score * 100) + '% match' }));

    // --- 2. Gemini for plain text explanation (no JSON) ---
    const geminiPrompt = `A specialized AI detection system classified this image as ${isAI ? 'AI GENERATED' : 'AUTHENTIC'}.

Examine the image and write exactly 4 bullet points explaining the specific visual evidence. Each bullet point should name a specific area of the image and what you observe there.

${isAI ? 'Focus on: skin texture, fingers/hands, hair, facial symmetry, background consistency, lighting, eyes, text in image.' : 'Focus on: film grain, skin imperfections, depth of field, shadow consistency, background detail, texture variation.'}

Format your response as exactly 4 lines, each starting with a dash:
- [area]: [observation]
- [area]: [observation]
- [area]: [observation]
- [area]: [observation]

Then on a new line write one sentence summary starting with SUMMARY:`;

    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: geminiPrompt }, { inline_data: { mime_type: mimeType, data: imageData } }] }],
          generationConfig: { maxOutputTokens: 1024, temperature: 0.0 }
        })
      }
    );

    const geminiData = await geminiRes.json();
    const raw = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text || '';

    // Parse plain text bullet points — much more reliable than JSON
    let indicators = [{ type: isAI ? 'ai' : 'real', text: isAI ? 'Classified as AI generated by detection model' : 'Classified as authentic by detection model' }, ...topGenerators];
    let summary = isAI ? 'This image was likely generated by an AI model.' : 'This image appears to be authentic.';

    if (raw) {
      const lines = raw.split('\n').map(l => l.trim()).filter(Boolean);
      const bullets = lines.filter(l => l.startsWith('-')).map(l => l.replace(/^-\s*/, '').trim()).filter(l => l.length > 10).slice(0, 4);
      const summaryLine = lines.find(l => l.startsWith('SUMMARY:'));

      if (bullets.length > 0) {
        indicators = [
          ...bullets.map(text => ({ type: isAI ? 'ai' : 'real', text })),
          ...topGenerators
        ];
      }
      if (summaryLine) {
        summary = summaryLine.replace('SUMMARY:', '').trim();
      }
    }

    return res.status(200).json({
      verdict,
      confidence: Math.max(aiScore, realScore),
      ai_probability: aiScore,
      authentic_probability: realScore,
      indicators,
      summary
    });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
